name: CI Test

on: [push, pull_request]

permissions:
  contents: read
  statuses: write

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run Prettier check
        run: npm run format:check

      - name: Run tests
        run: npm run test:all
        env:
          NODE_ENV: test

      - name: Build project
        run: npm run build

      - name: Notify Vercel (tests)
        if: >
          always() &&
          (github.event_name != 'pull_request' ||
           github.event.pull_request.head.repo.full_name == github.repository)
        uses: vercel/repository-dispatch/actions/status@v1
        with:
          name: "Vercel - gen-ai-photobooth: tests"
          github_token: ${{ secrets.GITHUB_TOKEN }}
